package com.kpg.diary.ui;

import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * The Class HeaderUi.
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
@Component("headerUi")
public class HeaderUi extends VerticalLayout implements View {

    protected HorizontalLayout horizontalLayout;

    /**
     * Instantiates a new header ui.
     */
    public HeaderUi() {
	Design.read(this);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.vaadin.navigator.View#enter(com.vaadin.navigator.ViewChangeListener.
     * ViewChangeEvent)
     */
    @Override
    public void enter(ViewChangeEvent event) {
	// TODO Auto-generated method stub
    }
}
